config/routes.rb
Rails.application.routes.draw do
  resources :matches
  root to: "users#index"

  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :update, :show]

  post '/matches/generate', to: 'matches#generate', as: :generate

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  has_and_belongs_to_many :users

  def self.generate(date = Date.today.strftime("%F"))
    students_without_match = User.select{|user| user[:admin] == false && user.matches.select{|match| match.date.strftime("%F") == date }.length < 1}
    student_ids = students_without_match.map{|student| student.id}.shuffle
    self.match_student(student_ids, date)
  end

  def self.match_student(students, date)
    students = self.assign_left_over(students, date) if students.length <= 2 && students.length > 0
    return if students.length == 0
    current_student = students.first
    match = self.make_match(students, current_student, date)
    students = students.select{|student| student != match && student != current_student}
    self.match_student(students, date)
  end

  def self.make_match(students, current_student, date)
    other_students = self.other_students(students, current_student)
    match = self.find_match(other_students, current_student)
    Match.create(date: date, user_ids: [match, current_student])
    match
  end

  def self.find_match(other_students, current_student)
    minimum_matched = 100000
    other_students.each do |other_student|
      matches = self.times_matched(other_student, current_student)
      if matches < minimum_matched
        minimum_matched = matches
        @matched_student = other_student
      end
      return @matched_student if minimum_matched == 0
    end
    @matched_student
  end

  def self.times_matched(other_student, current_student)
    matches =  User.find(current_student).matches.select{|match| match.user_ids.include?(other_student) && match.user_ids.include?(current_student)}.length ## faster than checking through matches
    matches
  end

  def self.other_students(students, current_student)
    other_students = students.select{|student| student != current_student }
    other_students
  end

  def self.assign_left_over(students, match_date)
    if students.length == 1
      assigned = self.assign_to_loner(students, match_date)
      return [] if assigned
    end
    Match.create(date: match_date, user_ids: students)
    return []
  end

  def self.assign_to_loner(students, match_date)
    unmatched = Match.select{|match| match.users.length == 1 && match.date.strftime("%F") == match_date }.first
    return false if(!unmatched)
    students << unmatched.users.first.id
    unmatched.update(user_ids: students)
    return true
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :matches

  validates :first_name, presence: true
  validates :last_name, presence: true


  def name
    "#{first_name} #{last_name}"
  end

  def todays_match
    match = matches.find{|hash| hash[:date] === Date.today}
    return if match == nil
    if match.users.length == 2
      match.users[0] == @user ? match.users[1].name : match.users[0].name
    else
      "No partner for today"
    end
  end

  def past_matches
    matches.select{|hash| hash[:date] < Date.today}
  end

  def self.toggle_admin(id)
    selected_user = User.find(id)
    admin_status = !selected_user.admin
    selected_user.update(admin: admin_status)
  end

end

app/controllers/api/matches_controller.rb
class Api::MatchesController < ApplicationController

  def index
    render status: 200, json: {
      matches: Match.all
    }.to_json
  end


end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def index
    render status: 200, json: {
      users: User.all
    }.to_json
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/is_admin.rb
module IsAdmin
 extend ActiveSupport::Concern

 private
   def is_admin?
     if !current_user
       redirect_to new_user_session_path
     else
       user = User.find(current_user.id)
       user.admin
     end
   end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  include IsAdmin
  before_action :is_admin?, only: [:index, :generate]
  before_action :authenticate_user!

  def index
    if !is_admin?
      redirect_to user_path(current_user.id)
    end
    @past_matches = Match.select{|match| match.date < Date.today}.sort_by{|match| match.date}
    @todays_matches = Match.select{|match| match.date == Date.today}
    @future_matches = Match.select{|match| match.date > Date.today}.sort_by{|match| match.date}
  end

  def show
    @match = Match.find(params[:id])
  end

  def generate
    Match.generate(params[:date])
    redirect_to matches_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include IsAdmin
  before_action :is_admin?, only: :index
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :update]

  def index
    if !is_admin?
      redirect_to user_path(current_user.id)
    end
    @users = User.all
  end

  def show
    if !@user.todays_match
      Match.generate
      redirect_to user_path(current_user.id)
    end
    redirect_to user_path(current_user.id) if current_user != @user unless current_user.admin
  end

  def update
    User.toggle_admin(params[:id])
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Find Your Match</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/matches/_match_maker.html.erb
<%= form_tag("/matches/generate", method: "post") do %>
  <label>Date:</label>
  <%= date_field_tag(:date, Date.today) %>
  <%= submit_tag("Generate matches") %>
<% end %>

app/views/matches/index.html.erb
<h1>All matches</h1>
<%= render 'match_maker' %>

<h3>Todays matches</h3>
<table style="width: 80%">
  <tr>
    <th>Match ID</th>
    <th>Date</th>
    <th>Students</th>
  </tr>
  <% @todays_matches.each do |match| %>
    <tr>
      <td><%= link_to match.id, match_path(match.id) %></td>
      <td>Date: <%= match.date %></td>
      <td>Students:</td>
      <td><%= match.users[0].name %><%= match.users.length == 1 ? "" : " & #{match.users[1].name}" %> </td>
    </tr>
  <% end %>
</table>

<h3>Past matches</h3>
<table style="width: 80%">
  <tr>
    <th>Match ID</th>
    <th>Date</th>
    <th>Students</th>
  </tr>
  <% @past_matches.each do |match| %>
    <tr>
      <td><%= link_to match.id, match_path(match.id) %></td>
      <td>Date: <%= match.date %></td>
      <td>Students:</td>
      <td><%= match.users[0].name %><%= match.users.length == 1 ? "" : " & #{match.users[1].name}" %> </td>
    </tr>
  <% end %>
</table>

<h3>Upcomming matches</h3>
<table style="width: 80%">
  <tr>
    <th>Match ID</th>
    <th>Date</th>
    <th>Students</th>
  </tr>
  <% @future_matches.each do |match| %>
    <tr>
      <td><%= link_to match.id, match_path(match.id) %></td>
      <td>Date: <%= match.date %></td>
      <td>Students:</td>
      <td><%= match.users[0].name %><%= match.users.length == 1 ? "" : " & #{match.users[1].name}" %> </td>
    </tr>
  <% end %>
</table>

app/views/matches/show.html.erb
<h1>Your match</h1>

<h4>Match id: <%= @match.id %></h4>
<h5>Date: <%= @match.date %></h5>
<h5>Students:</h5>
<% @match.users.each do |student| %>
  <p><%= student.first_name %> <%= student.last_name %></p>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <p>Hello, <%= current_user.name %>!</p>
          <% if current_user.admin %>
            <%= link_to "all users", users_path %>
            <%= link_to "all matches", matches_path %>
          <% else %>
          <%= link_to "My matches", user_path(current_user.id) %>
          <% end %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/users/index.html.erb
<h1>Users</h1>
<table style="width:80%">
  <tr>
    <th>Name</th>
    <th>email address</th>
    <th>Admin</th>
    <th>User ID</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user_path(user.id) %></td>
      <td><%= user.email %></td>
      <td><%= user.admin ? "Admin" : "Student" %></td>
      <td><%= user.id %></td>
      <td><%= button_to user.admin ? "Demote to student" : "Make admin", user_path(user.id), method: "put" %></td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h3><%= @user.admin ? "Admin" : "Student" %></h3>
<hr>
<h2>Todays match: <%= @user.todays_match %></h2>
<hr>

<h3>Past matches</h3>
<table style="width: 50%">
  <tr>
    <th>Date</th>
    <th>Match</th>
  </tr>
  <% @user.past_matches.each do |match| %>
    <tr>
      <td><%= match.date %></td>
      <td><p><%= match.users.first == @user? match.users.last.name : match.users.first.name %></p>
      </td>
    </tr>
  <% end %>
</table>